# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.14"
  amd64: "ghcr.io/home-assistant/amd64-base:3.14"
  armhf: "ghcr.io/home-assistant/armhf-base:3.14"
  armv7: "ghcr.io/home-assistant/armv7-base:3.14"
  i386: "ghcr.io/home-assistant/i386-base:3.14"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Uptime Kuma"
  org.opencontainers.image.description: "Uptime kuma addon for home assistant"
  org.opencontainers.image.source: "https://github.com/DomiiBunn/addons/tree/main/uptimeKuma"
args:
  TEMPIO_VERSION: "2021.09.0"
